services:
  web:
    build:
      context: ../..  # Go up two levels to project root
      dockerfile: CA2/part4/Dockerfile
    container_name: ca2-web-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:tcp://db:1521/~/testdb
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: password

  db:
    image: oscarfonts/h2:2.2.224
    container_name: ca2-database
    ports:
      - "1521:1521"  # TCP port for JDBC
      - "8082:8082"  # Web console port
    volumes:
      - db_data:/opt/h2-data
    environment:
      H2_OPTIONS: -ifNotExists

volumes:
  db_data: